export const CardCorp = (id: string) => {
    const list = [
        { id: 'C0', company: '신한' },
        { id: 'C1', company: '비씨' },
        { id: 'C2', company: '광주' },
        { id: 'C3', company: 'KB국민' },
        { id: 'C4', company: 'NH' },
        { id: 'C5', company: '롯데' },
        { id: 'C6', company: '산업' },
        { id: 'C7', company: '삼성' },
        { id: 'C8', company: '수협' },
        { id: 'C9', company: '씨티' },
        { id: 'CA', company: '외환' },
        { id: 'CB', company: '우리' },
        { id: 'CC', company: '전북' },
        { id: 'CD', company: '제주' },
        { id: 'CF', company: '하나-외환' },
        { id: 'CH', company: '현대' },
    ];
    
    return  list?.find((i: any) => i.id === id)?.company
};

export const BankCorp = (id: string) => {
    const list = [
        { id: '002', company: '산업은행' },
        { id: '003', company: '기업은행' },
        { id: '004', company: '국민은행' },
        { id: '005', company: '외환은행' },
        { id: '007', company: '수협' },
        { id: '011', company: '농협' },
        { id: '012', company: '지역농·축협' },
        { id: '020', company: '우리은행' },
        { id: '023', company: 'SC제일은행' },
        { id: '027', company: '씨티은행' },
        { id: '031', company: '대구은행' },
        { id: '032', company: '부산은행' },
        { id: '034', company: '광주은행' },
        { id: '035', company: '제주은행' },
        { id: '037', company: '전북은행' },
        { id: '039', company: '경남은행' },
        { id: '045', company: '새마을금고' },
        { id: '048', company: '신협' },
        { id: '050', company: '저축은행' },
        { id: '071', company: '우체국' },
        { id: '081', company: '하나은행' },
        { id: '088', company: '신한은행' },
        { id: '089', company: '케이뱅크' },
        { id: '090', company: '카카오뱅크' },
        { id: '092', company: '토스뱅크' },
        { id: '102', company: '대신저축은행' },
        { id: '103', company: '에스비아이저축은행' },
        { id: '104', company: '에이치케이저축은행' },
        { id: '105', company: '웰컴저축은행' },
        { id: '106', company: '신한저축은행' },
        { id: '209', company: '유안타증권' },
        { id: '218', company: 'KB증권' },
        { id: '221', company: '상상인증권' },
        { id: '222', company: '한양증권' },
        { id: '223', company: '리딩투자증권' },
        { id: '224', company: 'BNK투자증권' },
        { id: '225', company: 'IBK투자증권' },
        { id: '227', company: '다올투자증권' },
        { id: '230', company: '미래에셋' },
        { id: '238', company: '미래에셋' },
        { id: '240', company: '삼성증권' },
        { id: '243', company: '한국투자증권' },
        { id: '247', company: 'NH투자증권' },
        { id: '261', company: '교보증권' },
        { id: '262', company: '하이투자증권' },
        { id: '263', company: '현대차증권' },
        { id: '264', company: '키움증권' },
        { id: '265', company: '이베스트투자증권' },
        { id: '266', company: 'SK증권' },
        { id: '267', company: '대신증권' },
        { id: '269', company: '한화증권' },
        { id: '270', company: '하나금융투자' },
        { id: '278', company: '신한금융투자' },
        { id: '279', company: 'DB금융투자' },
        { id: '280', company: '유진투자증권' },
        { id: '287', company: '메리츠증권' },
        { id: '288', company: '카카오페이증권' },
        { id: '290', company: '부국증권' },
        { id: '291', company: '신영증권' },
        { id: '292', company: '케이프투자증권' },
        { id: '293', company: '한국증권금융' },
        { id: '294', company: '한국포스증권' },
        { id: '295', company: '우리종합금융' },
    ];
    return  list?.find((i: any) => i.id === id)?.company
};




